server:
  port: 3344

spring:
  application:
    name:  micro-service-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mavisguo/micro-service-cloud-config.git
          force-pull: true